// stdlib
#include <assert.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <errno.h>
// system
#include <fcntl.h>
#include <poll.h>
#include <unistd.h>
#include <arpa/inet.h>
#include <sys/socket.h>
#include <netinet/ip.h>
// C++
#include <vector>

static void msg(const char *msg){
    fprintf(stderr , "%s\n" , msg);
}
static void msg_errno(const char *msg) {
    fprintf(stderr, "[errno:%d] %s\n", errno, msg);
}
static void die(const char *msg){
    int err = errno;
    fprintf(stderr , "[%d] %s\n" , err, msg);
    abort();
}
static void fd_set_nb(int fd) {
    errno = 0;
    int flags = fcntl(fd, F_GETFL, 0);
    if (errno) {
        die("fcntl error");
        return;
    }

    flags |= O_NONBLOCK;

    errno = 0;
    (void)fcntl(fd, F_SETFL, flags);
    if (errno) {
        die("fcntl error");
    }
}

const size_t k_max_msg = 1024 * 1024; //1MB

// Represents a client connection, including its socket file descriptor,
// read/write/close intentions, and input/output buffers used in the server loop.
struct Conn{
    int fd = -1;
    bool want_read = false;
    bool want_write = false;
    bool want_close = false;

    //buffer input and output 
    std::vector<uint8_t> incoming; // data to be parsed by the application
    std::vector<uint8_t> outgoing; // response generated by the application
};

//appent to the back
static void buf_append(std::vector<uint8_t> &buf, const uint8_t *data, size_t len){
    size_t old_size = buf.size();
    buf.resize(old_size + len);
    memcpy(buf.data() + old_size, data, len);
}

// remove from the front
static void buf_consume(std::vector<uint8_t> &buf, size_t len){
    assert(len <= buf.size());
    if(len == buf.size()){
        buf.clear();
        return;
    }
    memmove(buf.data(), buf.data() + len, buf.size() - len);
    buf.resize(buf.size() - len);
}


static Conn *handle_accept(int fd){
    // accept
    struct sockaddr_in client_addr = {};
    socklen_t addrlen = sizeof(client_addr);
    int connfd = accept(fd, (struct sockaddr *)&client_addr, &addrlen);
    if(connfd < 0){
        return NULL;
    }

    //set the new connection fd t0 nonblocking mode
    fd_set_nb(connfd);
    //create a struct Conn
    Conn *conn = new Conn();
    conn->fd = connfd;
    conn->want_read = true; // read the 1st request
    return conn;
}

static bool try_one_request(Conn *conn){
    if(conn->incoming.size() < 4){
        return false; // want read
    }
    uint32_t len = 0;
    memcpy(&len, conn->incoming.data(), 4);
    if(len > k_max_msg){
        msg("too long message");
        conn->want_close = true;
        return false;
    }
    // message body
    if(4 + len > conn->incoming.size()){
        return false; 
    }
    const uint8_t *request = &conn->incoming[4];
    printf("client says: len:%d data:%.*s\n", len, len < 100 ? len:100, request);
    // generate the response
    buf_append(conn->outgoing, (const uint8_t *)&len, 4);
    buf_append(conn->outgoing, request, len);

    // remove the request mesage.
    buf_consume(conn->incoming, 4 + len);
    return true;

}

static void handle_write(Conn *conn){
    assert(conn->outgoing.size() > 0);
    ssize_t rv = write(conn->fd, conn->outgoing.data(), conn->outgoing.size());
    if(rv < 0){
        msg_errno("write() error");
        conn->want_close = true; // error handling
        return;
    }
    buf_consume(conn->outgoing, (size_t)rv);//remove written data from outgoing

    if(conn->outgoing.size() == 0){
        // all data written
        conn->want_read = true;
        conn->want_write = false;
    }// else: want write
}

static void handle_read(Conn *conn){
    // read some data
    uint8_t buf[64 * 1024];
    ssize_t rv = read(conn->fd, buf, sizeof(buf));
    if (rv < 0 && errno == EAGAIN) {
        return; // actually not ready
    }
    // handle IO error
    if (rv < 0) {
        msg_errno("read() error");
        conn->want_close = true;
        return; // want close
    }
    // handle EOF
    if (rv == 0) {
        if (conn->incoming.size() == 0) {
            msg("client closed");
        } else {
            msg("unexpected EOF");
        }
        conn->want_close = true;
        return; // want close
    }
    // got some new data
    buf_append(conn->incoming, buf, (size_t)rv);
    // parse requests and generate responses
    while (try_one_request(conn)) {}
    // update the readiness intention
    if (conn->outgoing.size() > 0) {    // has a response
        conn->want_read = false;
        conn->want_write = true;
        // The socket is likely ready to write in a request-response protocol,
        // try to write it without waiting for the next iteration.
        return handle_write(conn);
    }   // else: want read
}

int main(){
    int socketfd = socket(AF_INET, SOCK_STREAM, 0);
    if(socketfd < 0){
        die("socket()");
    }

    int val = 1;
    setsockopt(socketfd , SOL_SOCKET , SO_REUSEADDR, &val , sizeof(val));

    struct sockaddr_in addr  = {};
    addr.sin_family = AF_INET;
    addr.sin_port = ntohl(1234);
    addr.sin_addr.s_addr = htonl(INADDR_ANY);
    
    // bind 
    if(bind(socketfd, (const sockaddr *)&addr , sizeof(addr)) < 0){
        die("bind()");
    }

    // listen
    if(listen(socketfd, SOMAXCONN) < 0){
        die("listen()");
    }   
    
    // all the active connections , keyed by their socketfd
    std::vector<Conn *> fd2conn;
    // the event loop
    std::vector<struct pollfd> poll_args;

    while(true){
        poll_args.clear();
        //first add listening socket
        struct pollfd pfd = {socketfd, POLLIN, 0};
        poll_args.push_back(pfd);
        // rest are connection sockets
        for(Conn *conn : fd2conn){
            if(!conn) continue; // skip nullptr
            struct pollfd pfd;
            pfd.fd = conn->fd;
            pfd.events = 0;
            pfd.revents = 0;

            if(conn->want_read){
                pfd.events |= POLLIN;
            }
            if(conn->want_write){
                pfd.events |= POLLOUT;
            }
            poll_args.push_back(pfd);
        }

        // wait for readiness
        int rv = poll(poll_args.data(), (nfds_t)poll_args.size(), -1);
        if(rv < 0 && errno == EINTR){
            continue; // not an error
        }
        if(rv < 0){
            die("poll");
        }

        // handle the listening socket
        if(poll_args[0].revents){
            if(Conn *conn = handle_accept(socketfd)){
                //put it into map
                if(fd2conn.size() <= (size_t)conn->fd){
                    fd2conn.resize(conn->fd+1);
                }
                fd2conn[conn->fd] = conn;
            }
        }
        // handle connection sockets
        for(size_t i = 1; i < poll_args.size(); ++i){ // skip the 1st
            uint32_t ready = poll_args[i].revents;
            if ((size_t)poll_args[i].fd >= fd2conn.size() || fd2conn[poll_args[i].fd] == nullptr) {
                continue; // skip invalid or closed fd
            }
            Conn* conn = fd2conn[poll_args[i].fd];
            if(ready & POLLIN){
                handle_read(conn); //app logic
            }
            if(ready & POLLOUT){
                handle_write(conn); // app logic
            }

            // close the socket from socket error or application logic
            if((ready & POLLERR) || conn->want_close){
                (void)close(conn->fd);
                fd2conn[conn->fd] = NULL;
                delete conn;
            }
        }
    }
    return 0;
}
